// Centralized data configuration for categories, products, tours, and blog

export const navLinks = [
  { id: 'adventure-tours', name: 'ADVENTURE TOURS', slug: 'adventure-tours' },
  { id: 'camping-gear', name: 'CAMPING GEAR', slug: 'camping-gear' },
  { id: 'trekking-gear', name: 'TREKKING GEAR', slug: 'trekking-gear' },
  { id: 'climbing-gear', name: 'CLIMBING GEAR', slug: 'climbing-gear' },
  { id: 'shop-by-brand', name: 'SHOP BY BRAND', slug: 'shop-by-brand' },
  { id: 'imported-stuff', name: 'IMPORTED STUFF', slug: 'imported-stuff' },
  { id: 'campsites', name: 'CAMPSITES', slug: 'campsites' },
  { id: 'ecommerce-services', name: 'E-COMMERCE SERVICES', slug: 'ecommerce-services' },
  { id: 'blog', name: 'BLOG', slug: 'blog' },
]

// Mega Menu Dropdown Items for each nav link
export const megaMenuItems = {
  'adventure-tours': [
    { id: 'srilanka-cycling', name: 'Srilanka Cycling Tour', slug: '/adventure-tours/srilanka-cycling' },
    { id: 'srilanka-sightseeing', name: 'Srilanka Sight Seeing Tour', slug: '/adventure-tours/srilanka-sightseeing' },
    { id: 'mumbai-goa-cycling', name: 'Mumbai Goa Cycling', slug: '/adventure-tours/mumbai-goa-cycling' },
    { id: 'sandakphu-trek', name: 'Sandakphu Trek', slug: '/adventure-tours/sandakphu-trek' },
    { id: 'manali-leh-cycling', name: 'Manali Leh Khardungla Cycling', slug: '/adventure-tours/manali-leh-cycling' },
    { id: 'custom-himalayan-treks', name: 'Customised Himalayan Treks', slug: '/adventure-tours/custom-himalayan-treks' },
    { id: 'custom-cycling-tours', name: 'Customised Cycling Tours', slug: '/adventure-tours/custom-cycling-tours' },
    { id: 'training-camps', name: 'Training Camps', slug: '/adventure-tours/training-camps' },
    { id: 'family-camping', name: 'Family Camping', slug: '/adventure-tours/family-camping' },
    { id: 'adventure-support', name: 'Adventure Support for TV / Film', slug: '/adventure-tours/adventure-support' },
    { id: 'mountaineering-courses', name: 'Mountaineering Courses – India', slug: '/adventure-tours/mountaineering-courses' },
  ],
  'camping-gear': [
    { id: 'tents', name: 'CAMPING TENTS', slug: '/camping-gear/tents' },
    { id: 'sleeping-bags', name: 'SLEEPING BAGS & MATS', slug: '/camping-gear/sleeping-bags' },
    { id: 'survival-gear', name: 'SURVIVAL GEAR', slug: '/camping-gear/survival-gear' },
    { id: 'guns-rifles', name: 'GUNS AND RIFLES', slug: '/camping-gear/guns-rifles' },
    { id: 'camping-stoves-bbq', name: 'CAMPING STOVES & BBQ', slug: '/camping-gear/stoves-bbq' },
    { id: 'camp-kitchen', name: 'CAMP KITCHEN', slug: '/camping-gear/camp-kitchen' },
    { id: 'ride-travel', name: 'RIDE AND TRAVEL', slug: '/camping-gear/ride-travel' },
    { id: 'rentals', name: 'CAMPING GEAR ON RENT', slug: '/camping-gear/rentals' },
  ],
  'trekking-gear': [
    { id: 'footwear', name: 'FOOTWEAR', slug: '/trekking-gear/footwear' },
    { id: 'socks-gloves', name: 'SOCKS & GLOVES', slug: '/trekking-gear/socks-gloves' },
    { id: 'hydration', name: 'HYDRATION', slug: '/trekking-gear/hydration' },
    { id: 'sports-apparel', name: 'SPORTS APPAREL', slug: '/trekking-gear/sports-apparel' },
    { id: 'lights-torches', name: 'LIGHTS & TORCHES', slug: '/trekking-gear/lights-torches' },
    { id: 'sunglasses', name: 'SUNGLASSES', slug: '/trekking-gear/sunglasses' },
    { id: 'rucksack-pouch', name: 'RUCKSACK & POUCH', slug: '/trekking-gear/rucksack-pouch' },
    { id: 'trekking-accessories', name: 'TREKKING ACCESSORIES', slug: '/trekking-gear/accessories' },
  ],
  'climbing-gear': [
    { id: 'ascenders-pulleys', name: 'ASCENDERS & PULLEYS', slug: '/climbing-gear/ascenders-pulleys' },
    { id: 'descenders-belays', name: 'DESCENDERS & BELAYS', slug: '/climbing-gear/descenders-belays' },
    { id: 'carabiners-quickdraws', name: 'CARABINERS & QUICKDRAWS', slug: '/climbing-gear/carabiners-quickdraws' },
    { id: 'climbing-holds', name: 'CLIMBING HOLDS', slug: '/climbing-gear/climbing-holds' },
    { id: 'harness-tape', name: 'CLIMBING HARNESS AND TAPE', slug: '/climbing-gear/harness-tape' },
    { id: 'helmets', name: 'CLIMBING HELMETS', slug: '/climbing-gear/helmets' },
    { id: 'anchors', name: 'CLIMBING ANCHORS', slug: '/climbing-gear/anchors' },
    { id: 'ropes', name: 'CLIMBING ROPES', slug: '/climbing-gear/ropes' },
    { id: 'work-safety', name: 'WORK SAFETY EQUIPMENT', slug: '/climbing-gear/work-safety' },
    { id: 'crash-pads', name: 'CRASH PADS', slug: '/climbing-gear/crash-pads' },
  ],
  'shop-by-brand': [
    { id: 'add-gear', name: 'Add Gear', slug: '/shop-by-brand/add-gear' },
    { id: 'black-diamond', name: 'Black Diamond', slug: '/shop-by-brand/black-diamond' },
    { id: 'caustic', name: 'Caustic', slug: '/shop-by-brand/caustic' },
    { id: 'coleman', name: 'Coleman', slug: '/shop-by-brand/coleman' },
    { id: 'ctr-shoes', name: 'CTR Shoes', slug: '/shop-by-brand/ctr-shoes' },
    { id: 'edelrid', name: 'Edelrid', slug: '/shop-by-brand/edelrid' },
    { id: 'entre-prises', name: 'Entre Prises', slug: '/shop-by-brand/entre-prises' },
    { id: 'fenix', name: 'Fenix', slug: '/shop-by-brand/fenix' },
    { id: 'gokyo', name: 'Gokyo', slug: '/shop-by-brand/gokyo' },
    { id: 'gipfel', name: 'Gipfel', slug: '/shop-by-brand/gipfel' },
    { id: 'hans', name: 'Hans', slug: '/shop-by-brand/hans' },
    { id: 'karrimor', name: 'Karrimor', slug: '/shop-by-brand/karrimor' },
    { id: 'koromount', name: 'Koromount', slug: '/shop-by-brand/koromount' },
    { id: 'kwiklander', name: 'Kwiklander', slug: '/shop-by-brand/kwiklander' },
    { id: 'lowe-alpine', name: 'Lowe Alpine', slug: '/shop-by-brand/lowe-alpine' },
    { id: 'mountcraft', name: 'Mountcraft', slug: '/shop-by-brand/mountcraft' },
    { id: 'mund', name: 'Mund', slug: '/shop-by-brand/mund' },
    { id: 'osprey', name: 'Osprey', slug: '/shop-by-brand/osprey' },
    { id: 'petzl', name: 'Petzl', slug: '/shop-by-brand/petzl' },
    { id: 'reccy', name: 'Reccy', slug: '/shop-by-brand/reccy' },
    { id: 'rock-empire', name: 'Rock Empire', slug: '/shop-by-brand/rock-empire' },
    { id: 'precihole-guns', name: 'Precihole Guns', slug: '/shop-by-brand/precihole-guns' },
    { id: 'sea-to-summit', name: 'Sea to Summit', slug: '/shop-by-brand/sea-to-summit' },
    { id: 'tendon', name: 'Tendon', slug: '/shop-by-brand/tendon' },
    { id: 'trek-n-ride', name: 'Trek \'N\' Ride', slug: '/shop-by-brand/trek-n-ride' },
    { id: 'trimm', name: 'Trimm', slug: '/shop-by-brand/trimm' },
    { id: 'vertical', name: 'Vertical', slug: '/shop-by-brand/vertical' },
    { id: 'warmee', name: 'Warmee', slug: '/shop-by-brand/warmee' },
    { id: 'n-rit', name: 'N-rit', slug: '/shop-by-brand/n-rit' },
    { id: 'tatonka', name: 'Tatonka', slug: '/shop-by-brand/tatonka' },
  ],
  'imported-stuff': [
    { id: 'bags-luggage', name: 'Bags and Luggage', slug: '/imported-stuff/bags-luggage' },
    { id: 'fashion-accessories', name: 'Fashion Accessories', slug: '/imported-stuff/fashion-accessories' },
    { id: 'home-kitchen', name: 'Home & Kitchen', slug: '/imported-stuff/home-kitchen' },
    { id: 'beach-house-alibaug', name: 'BEACH HOUSE - ALIBAUG', slug: '/imported-stuff/beach-house-alibaug' },
  ],
  'campsites': [
    { id: 'kondgaon-dam', name: 'KONDGAON DAM', slug: '/campsites/kondgaon-dam' },
    { id: 'karjat-farm-house', name: 'KARJAT FARM HOUSE', slug: '/campsites/karjat-farm-house' },
    { id: 'bungalow-alibaug', name: 'BUNGALOW AT ALIBAUG', slug: '/campsites/bungalow-alibaug' },
    { id: 'beach-house-alibaug', name: 'BEACH HOUSE - ALIBAUG', slug: '/campsites/beach-house-alibaug' },
  ],
  'ecommerce-services': [
    { id: 'amazon-account', name: 'Amazon Account management', slug: '/ecommerce-services/amazon-account' },
    { id: 'amazon-seller-aggregator', name: 'Amazon Seller Aggregator Program', slug: '/ecommerce-services/amazon-seller-aggregator' },
    { id: 'ecommerce-website', name: 'E-commerce Website', slug: '/ecommerce-services/ecommerce-website' },
  ],
  'blog': [
    { id: 'blog-category-1', name: 'Trekking Guides', slug: '/blog/trekking' },
    { id: 'blog-category-2', name: 'Camping Tips', slug: '/blog/camping' },
    { id: 'blog-category-3', name: 'Gear Reviews', slug: '/blog/reviews' },
    { id: 'blog-category-4', name: 'Adventure Stories', slug: '/blog/stories' },
  ],
}

export const categories = [
  {
    id: 'trekking',
    name: 'Trekking',
    slug: 'trekking-gear',
    description: 'Essential gear for mountain treks and hiking adventures',
    image: 'https://images.unsplash.com/photo-1551524164-6cf77f7f7e6c?w=800&h=600&fit=crop',
  },
  {
    id: 'camping',
    name: 'Camping',
    slug: 'camping-gear',
    description: 'Tents, sleeping bags, and camping essentials for outdoor stays',
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800&h=600&fit=crop',
  },
  {
    id: 'climbing',
    name: 'Climbing',
    slug: 'climbing-gear',
    description: 'Professional climbing equipment and safety gear',
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=800&h=600&fit=crop',
  },
]

export const adventureTours = [
  {
    id: 'tour-1',
    name: 'Himalayan Base Camp Trek',
    location: 'Himachal Pradesh',
    duration: '7 Days',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    badge: 'Popular',
    rating: 4.9,
  },
  {
    id: 'tour-2',
    name: 'Desert Safari Adventure',
    location: 'Rajasthan',
    duration: '3 Days',
    price: 12999,
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=600&fit=crop',
    badge: 'New',
    rating: 4.7,
  },
  {
    id: 'tour-3',
    name: 'Western Ghats Exploration',
    location: 'Kerala',
    duration: '5 Days',
    price: 18999,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    badge: null,
    rating: 4.8,
  },
  {
    id: 'tour-4',
    name: 'Rock Climbing Expedition',
    location: 'Maharashtra',
    duration: '2 Days',
    price: 8999,
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=800&h=600&fit=crop',
    badge: 'Popular',
    rating: 4.9,
  },
  {
    id: 'tour-5',
    name: 'Jungle Camping Experience',
    location: 'Madhya Pradesh',
    duration: '4 Days',
    price: 15999,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800&h=600&fit=crop',
    badge: null,
    rating: 4.6,
  },
  {
    id: 'tour-6',
    name: 'Coastal Adventure Trail',
    location: 'Goa',
    duration: '3 Days',
    price: 11999,
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=600&fit=crop',
    badge: 'New',
    rating: 4.7,
  },
]

export const gearProducts = [
  {
    id: 'gear-1',
    name: 'Premium Trekking Backpack 60L',
    description: 'Lightweight, durable backpack with multiple compartments',
    price: 5499,
    originalPrice: 6999,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 124,
    inStock: true,
  },
  {
    id: 'gear-2',
    name: '4-Season Camping Tent',
    description: 'Weather-resistant tent for all seasons',
    price: 12999,
    originalPrice: 15999,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews: 89,
    inStock: true,
  },
  {
    id: 'gear-3',
    name: 'Professional Climbing Harness',
    description: 'Comfortable harness with gear loops',
    price: 4999,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  {
    id: 'gear-4',
    name: 'Ultra-Light Sleeping Bag',
    description: 'Compact sleeping bag rated for -10°C',
    price: 6999,
    originalPrice: 8999,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 203,
    inStock: true,
  },
  {
    id: 'gear-5',
    name: 'Trekking Poles Set',
    description: 'Adjustable carbon fiber trekking poles',
    price: 2999,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1551524164-6cf77f7f7e6c?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews: 98,
    inStock: true,
  },
  {
    id: 'gear-6',
    name: 'Waterproof Hiking Boots',
    description: 'Premium boots with superior grip',
    price: 7999,
    originalPrice: 9999,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews: 312,
    inStock: true,
  },
  {
    id: 'gear-7',
    name: 'Portable Camping Stove',
    description: 'Compact gas stove for outdoor cooking',
    price: 2499,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 145,
    inStock: true,
  },
  {
    id: 'gear-8',
    name: 'Adventure Watch Pro',
    description: 'GPS-enabled watch with altimeter',
    price: 14999,
    originalPrice: 18999,
    image: 'https://images.unsplash.com/photo-1523275125684-513031cd5811?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 267,
    inStock: true,
  },
]

export const whyChooseUs = [
  {
    id: 'trust',
    icon: 'Shield',
    title: 'Trusted Quality',
    description: 'Premium gear tested by professional adventurers',
  },
  {
    id: 'shipping',
    icon: 'Truck',
    title: 'Fast Shipping',
    description: 'Quick delivery across India with secure packaging',
  },
  {
    id: 'support',
    icon: 'Headphones',
    title: 'Expert Support',
    description: '24/7 customer support from adventure enthusiasts',
  },
  {
    id: 'warranty',
    icon: 'Award',
    title: 'Warranty Coverage',
    description: 'Comprehensive warranty on all products',
  },
]

export const footwearProducts = [
  {
    id: 'footwear-1',
    name: 'Black Lightweight Trekking Shoes',
    description: 'Comfortable lightweight trekking shoes perfect for day hikes',
    price: 1599,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    badge: 'New Arrival',
    color: 'Black',
    size: ['7', '8', '9', '10'],
    brand: 'CTR',
  },
  {
    id: 'footwear-2',
    name: 'Black and Red High-Ankle Trekking Shoes',
    description: 'High-ankle support trekking boots with anti-skid sole',
    price: 1699,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 124,
    inStock: true,
    badge: 'New Arrival',
    color: 'Black/Red',
    size: ['7', '8', '9', '10', '11'],
    brand: 'CTR',
  },
  {
    id: 'footwear-3',
    name: 'Black Men\'s/Women\'s Trekking Shoes',
    description: 'Versatile trekking shoes suitable for both men and women',
    price: 1399,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews: 156,
    inStock: true,
    color: 'Black',
    size: ['6', '7', '8', '9', '10'],
    brand: 'CTR',
  },
  {
    id: 'footwear-4',
    name: 'Dark Blue Women\'s/Kids\' Trekking Shoes',
    description: 'Comfortable trekking shoes for women and kids with orange accents',
    price: 1399,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.5,
    reviews: 98,
    inStock: true,
    color: 'Dark Blue',
    size: ['4', '5', '6', '7', '8'],
    brand: 'CTR',
  },
  {
    id: 'footwear-5',
    name: 'Mund Cross Mountain Socks',
    description: 'High-quality hiking socks with MUND logo',
    price: 700,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    rating: 4.4,
    reviews: 67,
    inStock: true,
    color: 'Grey/White',
    size: ['One Size'],
    brand: 'MUND',
  },
  {
    id: 'footwear-6',
    name: 'Ice Grip Snow Shoe Grip',
    description: 'Removable ice grips for snow and ice conditions',
    price: 1250,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews: 112,
    inStock: true,
    color: 'Yellow/Grey',
    size: ['One Size'],
    brand: 'Add-gear',
  },
  {
    id: 'footwear-7',
    name: 'Ice Cleats Traction Crampons',
    description: 'Professional ice cleats for mountaineering and ice climbing',
    price: 1299,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 145,
    inStock: false,
    color: 'Black/Yellow',
    size: ['One Size'],
    brand: 'Add-gear',
    availability: 'Available on request',
  },
  {
    id: 'footwear-8',
    name: 'CTR HIGH ANKLE Trekking Shoes Anti-Skid',
    description: 'High-ankle trekking boots with superior anti-skid technology',
    price: 1699,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 203,
    inStock: true,
    color: 'Black',
    size: ['7', '8', '9', '10', '11'],
    brand: 'CTR',
  },
  {
    id: 'footwear-9',
    name: 'CTR Regular Trekking Shoes Anti-Skid Hiking',
    description: 'Regular trekking shoes with anti-skid hiking sole',
    price: 1399,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews: 178,
    inStock: true,
    badge: 'New Arrival',
    color: 'Olive Green',
    size: ['7', '8', '9', '10'],
    brand: 'CTR',
  },
  {
    id: 'footwear-10',
    name: 'Add-gear Drawstring Stopper Cord Lock',
    description: 'Drawstring stopper cord lock for shoelace and paracord',
    price: 149,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    rating: 4.3,
    reviews: 234,
    inStock: true,
    color: 'Black',
    size: ['One Size'],
    brand: 'Add-gear',
  },
  {
    id: 'footwear-11',
    name: 'Gipfel Alpine Gaiters',
    description: 'Professional alpine gaiters with GIPFEL branding',
    price: 899,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.5,
    reviews: 156,
    inStock: true,
    color: 'Black',
    size: ['One Size'],
    brand: 'GIPFEL',
  },
  {
    id: 'footwear-12',
    name: 'Outdoor Snow Climbing Mountaineering Gaiters',
    description: 'Heavy-duty mountaineering gaiters for snow and ice conditions',
    price: 1299,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 189,
    inStock: true,
    color: 'Red',
    size: ['One Size'],
    brand: 'Add-gear',
  },
]

export const products = {
  'trekking-gear': gearProducts.slice(0, 6),
  'camping-gear': gearProducts.slice(2, 8),
  'climbing-gear': gearProducts.filter((p) => p.name.toLowerCase().includes('climbing') || p.name.toLowerCase().includes('harness') || p.name.toLowerCase().includes('rope')),
  'footwear': footwearProducts,
}

export const blogPosts = [
  {
    id: 'blog-1',
    title: 'Essential Gear for Your First Himalayan Trek',
    excerpt: 'Everything you need to know before embarking on your first high-altitude adventure',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    date: '2024-01-15',
    author: 'Adventure Team',
    category: 'Trekking',
  },
  {
    id: 'blog-2',
    title: 'Top 10 Camping Spots in India',
    excerpt: 'Discover the most beautiful and accessible camping destinations across India',
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800&h=600&fit=crop',
    date: '2024-01-10',
    author: 'Adventure Team',
    category: 'Camping',
  },
  {
    id: 'blog-3',
    title: 'Rock Climbing Safety Guide',
    excerpt: 'Learn essential safety practices for indoor and outdoor rock climbing',
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=800&h=600&fit=crop',
    date: '2024-01-05',
    author: 'Adventure Team',
    category: 'Climbing',
  },
]

export const cyclingToursCarousel = [
  {
    id: 'khardungla-cycling',
    title: 'Khardungla',
    subtitle: 'Cycling Tour',
    date: '5 Aug to 9 Sept 2023',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=600&fit=crop',
    slug: '/adventure-tours/khardungla-cycling',
  },
  {
    id: 'mumbai-goa-coastal',
    title: 'Mumbai - Goa',
    subtitle: 'Coastal Cycling',
    date: 'Coming up - Jan 2024',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=600&fit=crop',
    slug: '/adventure-tours/mumbai-goa-coastal',
  },
  {
    id: 'goa-ooty-cycling',
    title: 'Blue Sea to Blue Hills',
    subtitle: 'Goa - Ooty Cycling',
    date: 'Coming up - Jan 2024',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop',
    slug: '/adventure-tours/goa-ooty-cycling',
  },
  {
    id: 'sri-lanka-cycling',
    title: 'SRI LANKA CYCLING TOUR',
    subtitle: 'JAN 2024',
    date: 'JAN 2024',
    image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=1200&h=600&fit=crop',
    slug: '/adventure-tours/sri-lanka-cycling',
    details: [
      '9 Nights in 3 Star hotels',
      'Trained cycling guides',
      'Mechanic all along the trip',
      'A support / backup vehicle',
      'A/C Luxury Coach for cyclists',
      'All meals 3 times a day',
      'High quality MTBs',
      'Complementary Sightseeing',
    ],
  },
]

export const siteConfig = {
  name: 'Adventure India',
  url: 'https://www.addventureindia.com',
  description: 'Premium outdoor adventure gear and equipment for explorers across India',
  defaultSeo: {
    title: 'Adventure India - Premium Outdoor Gear & Equipment',
    description: 'Discover premium outdoor adventure gear, hiking equipment, and climbing gear. Trusted by adventurers across India.',
    keywords: 'outdoor gear, adventure equipment, hiking gear, climbing equipment, India adventure',
  },
}
