// Centralized data configuration for categories and products

export const categories = [
  {
    id: 'footwear',
    name: 'Footwear',
    slug: 'footwear',
    description: 'Premium hiking boots, trail running shoes, and outdoor footwear for every adventure',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop',
    seo: {
      title: 'Footwear | Adventure India - Premium Hiking Boots & Trail Shoes',
      description: 'Discover premium hiking boots, trail running shoes, and outdoor footwear. Durable, comfortable, and designed for Indian terrain.',
      keywords: 'hiking boots, trail shoes, outdoor footwear, adventure shoes, trekking boots',
    },
  },
  {
    id: 'hydration',
    name: 'Hydration',
    slug: 'hydration',
    description: 'Water bottles, hydration packs, and gear to keep you hydrated on your adventures',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&h=600&fit=crop',
    seo: {
      title: 'Hydration Gear | Adventure India - Water Bottles & Hydration Packs',
      description: 'Stay hydrated on your adventures with premium water bottles, hydration packs, and gear designed for outdoor enthusiasts.',
      keywords: 'water bottles, hydration packs, outdoor hydration, adventure gear, trekking essentials',
    },
  },
  {
    id: 'climbing-ropes',
    name: 'Climbing Ropes',
    slug: 'climbing-ropes',
    description: 'Professional climbing ropes, harnesses, and safety equipment for rock climbing',
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=800&h=600&fit=crop',
    seo: {
      title: 'Climbing Ropes & Gear | Adventure India - Professional Climbing Equipment',
      description: 'Professional climbing ropes, harnesses, and safety equipment. Trusted by climbers across India for safety and performance.',
      keywords: 'climbing ropes, climbing gear, rock climbing equipment, harnesses, climbing safety',
    },
  },
]

export const products = {
  footwear: [
    {
      id: 'fw-001',
      name: 'Trail Master Pro Hiking Boots',
      description: 'Waterproof hiking boots with superior grip and ankle support for challenging terrains',
      price: 5499,
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
      rating: 4.8,
      inStock: true,
    },
    {
      id: 'fw-002',
      name: 'Lightweight Trail Runner',
      description: 'Ultra-light trail running shoes perfect for day hikes and fast-paced adventures',
      price: 3999,
      image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=600&fit=crop',
      rating: 4.6,
      inStock: true,
    },
    {
      id: 'fw-003',
      name: 'Mountain Trekker Boots',
      description: 'Heavy-duty boots designed for multi-day treks and extreme weather conditions',
      price: 6999,
      image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&h=600&fit=crop',
      rating: 4.9,
      inStock: true,
    },
    {
      id: 'fw-004',
      name: 'Desert Explorer Sandals',
      description: 'Breathable sandals ideal for hot climates and desert adventures',
      price: 2499,
      image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&h=600&fit=crop',
      rating: 4.5,
      inStock: true,
    },
    {
      id: 'fw-005',
      name: 'Urban Adventure Sneakers',
      description: 'Versatile sneakers that transition from city streets to light trails',
      price: 3499,
      image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=600&fit=crop',
      rating: 4.7,
      inStock: true,
    },
    {
      id: 'fw-006',
      name: 'Winter Expedition Boots',
      description: 'Insulated boots with superior warmth for high-altitude and winter adventures',
      price: 7999,
      image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&h=600&fit=crop',
      rating: 4.8,
      inStock: false,
    },
  ],
  hydration: [
    {
      id: 'hy-001',
      name: 'Adventure Hydration Pack 2L',
      description: 'Lightweight hydration pack with 2L capacity and multiple storage pockets',
      price: 1999,
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop',
      rating: 4.7,
      inStock: true,
    },
    {
      id: 'hy-002',
      name: 'Stainless Steel Water Bottle 1L',
      description: 'Durable stainless steel bottle that keeps drinks cold for 24 hours',
      price: 899,
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop',
      rating: 4.6,
      inStock: true,
    },
    {
      id: 'hy-003',
      name: 'Collapsible Water Bottle 750ml',
      description: 'Space-saving collapsible bottle perfect for day hikes and travel',
      price: 599,
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop',
      rating: 4.5,
      inStock: true,
    },
    {
      id: 'hy-004',
      name: 'Premium Hydration Bladder 3L',
      description: 'Large capacity hydration bladder with quick-release valve',
      price: 2499,
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop',
      rating: 4.8,
      inStock: true,
    },
    {
      id: 'hy-005',
      name: 'Insulated Water Bottle 1.5L',
      description: 'Double-wall insulated bottle keeps drinks cold or hot for extended periods',
      price: 1299,
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop',
      rating: 4.7,
      inStock: true,
    },
    {
      id: 'hy-006',
      name: 'Filter Water Bottle with Purifier',
      description: 'Advanced filtration system removes 99.9% of bacteria and protozoa',
      price: 3499,
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop',
      rating: 4.9,
      inStock: true,
    },
  ],
  'climbing-ropes': [
    {
      id: 'cr-001',
      name: 'Dynamic Climbing Rope 10mm',
      description: 'Professional dynamic rope with UIAA certification for sport and trad climbing',
      price: 8999,
      image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=600&h=600&fit=crop',
      rating: 4.9,
      inStock: true,
    },
    {
      id: 'cr-002',
      name: 'Static Rope 11mm',
      description: 'Heavy-duty static rope for rappelling and rescue operations',
      price: 7499,
      image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=600&h=600&fit=crop',
      rating: 4.8,
      inStock: true,
    },
    {
      id: 'cr-003',
      name: 'Climbing Harness Pro',
      description: 'Comfortable and adjustable harness with gear loops and padding',
      price: 4999,
      image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=600&h=600&fit=crop',
      rating: 4.7,
      inStock: true,
    },
    {
      id: 'cr-004',
      name: 'Quickdraw Set (6 pack)',
      description: 'Lightweight quickdraws with wiregate carabiners for sport climbing',
      price: 3999,
      image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=600&h=600&fit=crop',
      rating: 4.6,
      inStock: true,
    },
    {
      id: 'cr-005',
      name: 'Belay Device with Guide Mode',
      description: 'Versatile belay device suitable for single and multi-pitch climbs',
      price: 2499,
      image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=600&h=600&fit=crop',
      rating: 4.8,
      inStock: true,
    },
    {
      id: 'cr-006',
      name: 'Climbing Helmet Pro',
      description: 'Lightweight helmet with ventilation and adjustable fit system',
      price: 3499,
      image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=600&h=600&fit=crop',
      rating: 4.7,
      inStock: true,
    },
  ],
}

export const featuredProducts = [
  products.footwear[0],
  products.hydration[0],
  products['climbing-ropes'][0],
  products.footwear[1],
]

export const siteConfig = {
  name: 'Adventure India',
  url: 'https://www.addventureindia.com',
  description: 'Premium outdoor adventure gear and equipment for explorers across India',
  defaultSeo: {
    title: 'Adventure India - Premium Outdoor Gear & Equipment',
    description: 'Discover premium outdoor adventure gear, hiking equipment, and climbing gear. Trusted by adventurers across India.',
    keywords: 'outdoor gear, adventure equipment, hiking gear, climbing equipment, India adventure',
  },
}

