// Centralized data configuration for categories, products, tours, and blog

export const navLinks = [
  { id: 'adventure-tours', name: 'ADVENTURE TOURS', slug: 'adventure-tours' },
  { id: 'camping-gear', name: 'CAMPING GEAR', slug: 'camping-gear' },
  { id: 'trekking-gear', name: 'TREKKING GEAR', slug: 'trekking-gear' },
  { id: 'climbing-gear', name: 'CLIMBING GEAR', slug: 'climbing-gear' },
  { id: 'shop-by-brand', name: 'SHOP BY BRAND', slug: 'shop-by-brand' },
  { id: 'imported-stuff', name: 'IMPORTED STUFF', slug: 'imported-stuff' },
  { id: 'campsites', name: 'CAMPSITES', slug: 'campsites' },
  { id: 'ecommerce-services', name: 'E-COMMERCE SERVICES', slug: 'ecommerce-services' },
  { id: 'blog', name: 'BLOG', slug: 'blog' },
]

// Mega Menu Dropdown Items for each nav link
export const megaMenuItems = {
  'adventure-tours': [
    { id: 'srilanka-cycling', name: 'Srilanka Cycling Tour', slug: '/adventure-tours/srilanka-cycling' },
    { id: 'srilanka-sightseeing', name: 'Srilanka Sight Seeing Tour', slug: '/adventure-tours/srilanka-sightseeing' },
    { id: 'mumbai-goa-cycling', name: 'Mumbai Goa Cycling', slug: '/adventure-tours/mumbai-goa-cycling' },
    { id: 'sandakphu-trek', name: 'Sandakphu Trek', slug: '/adventure-tours/sandakphu-trek' },
    { id: 'manali-leh-cycling', name: 'Manali Leh Khardungla Cycling', slug: '/adventure-tours/manali-leh-cycling' },
    { id: 'custom-himalayan-treks', name: 'Customised Himalayan Treks', slug: '/adventure-tours/custom-himalayan-treks' },
    { id: 'custom-cycling-tours', name: 'Customised Cycling Tours', slug: '/adventure-tours/custom-cycling-tours' },
    { id: 'training-camps', name: 'Training Camps', slug: '/adventure-tours/training-camps' },
    { id: 'family-camping', name: 'Family Camping', slug: '/adventure-tours/family-camping' },
    { id: 'adventure-support', name: 'Adventure Support for TV / Film', slug: '/adventure-tours/adventure-support' },
    { id: 'mountaineering-courses', name: 'Mountaineering Courses – India', slug: '/adventure-tours/mountaineering-courses' },
  ],
  'camping-gear': [
    { id: 'tents', name: 'CAMPING TENTS', slug: '/camping-gear/tents' },
    { id: 'sleeping-bags', name: 'SLEEPING BAGS & MATS', slug: '/camping-gear/sleeping-bags' },
    { id: 'survival-gear', name: 'SURVIVAL GEAR', slug: '/camping-gear/survival-gear' },
    { id: 'guns-rifles', name: 'GUNS AND RIFLES', slug: '/camping-gear/guns-rifles' },
    { id: 'camping-stoves-bbq', name: 'CAMPING STOVES & BBQ', slug: '/camping-gear/stoves-bbq' },
    { id: 'camp-kitchen', name: 'CAMP KITCHEN', slug: '/camping-gear/camp-kitchen' },
    { id: 'ride-travel', name: 'RIDE AND TRAVEL', slug: '/camping-gear/ride-travel' },
    { id: 'rentals', name: 'CAMPING GEAR ON RENT', slug: '/camping-gear/rentals' },
  ],
  'trekking-gear': [
    { id: 'footwear', name: 'FOOTWEAR', slug: '/trekking-gear/footwear' },
    { id: 'socks-gloves', name: 'SOCKS & GLOVES', slug: '/trekking-gear/socks-gloves' },
    { id: 'hydration', name: 'HYDRATION', slug: '/trekking-gear/hydration' },
    { id: 'sports-apparel', name: 'SPORTS APPAREL', slug: '/trekking-gear/sports-apparel' },
    { id: 'lights-torches', name: 'LIGHTS & TORCHES', slug: '/trekking-gear/lights-torches' },
    { id: 'sunglasses', name: 'SUNGLASSES', slug: '/trekking-gear/sunglasses' },
    { id: 'rucksack-pouch', name: 'RUCKSACK & POUCH', slug: '/trekking-gear/rucksack-pouch' },
    { id: 'trekking-accessories', name: 'TREKKING ACCESSORIES', slug: '/trekking-gear/accessories' },
  ],
  'climbing-gear': [
    { id: 'ropes', name: 'Climbing Ropes', slug: '/climbing-gear/ropes' },
    { id: 'harnesses', name: 'Harnesses', slug: '/climbing-gear/harnesses' },
    { id: 'carabiners', name: 'Carabiners', slug: '/climbing-gear/carabiners' },
    { id: 'helmets', name: 'Climbing Helmets', slug: '/climbing-gear/helmets' },
    { id: 'shoes', name: 'Climbing Shoes', slug: '/climbing-gear/shoes' },
    { id: 'protection', name: 'Protection Gear', slug: '/climbing-gear/protection' },
  ],
  'shop-by-brand': [
    { id: 'brand-1', name: 'Brand A', slug: '/shop-by-brand/brand-a' },
    { id: 'brand-2', name: 'Brand B', slug: '/shop-by-brand/brand-b' },
    { id: 'brand-3', name: 'Brand C', slug: '/shop-by-brand/brand-c' },
    { id: 'brand-4', name: 'Brand D', slug: '/shop-by-brand/brand-d' },
    { id: 'brand-5', name: 'Brand E', slug: '/shop-by-brand/brand-e' },
    { id: 'brand-6', name: 'Brand F', slug: '/shop-by-brand/brand-f' },
  ],
  'imported-stuff': [
    { id: 'imported-gear-1', name: 'Premium Imported Gear', slug: '/imported-stuff/premium' },
    { id: 'imported-gear-2', name: 'International Brands', slug: '/imported-stuff/brands' },
    { id: 'imported-gear-3', name: 'Specialty Items', slug: '/imported-stuff/specialty' },
  ],
  'campsites': [
    { id: 'campsite-1', name: 'Himalayan Campsites', slug: '/campsites/himalayan' },
    { id: 'campsite-2', name: 'Beach Campsites', slug: '/campsites/beach' },
    { id: 'campsite-3', name: 'Forest Campsites', slug: '/campsites/forest' },
    { id: 'campsite-4', name: 'Desert Campsites', slug: '/campsites/desert' },
  ],
  'ecommerce-services': [
    { id: 'service-1', name: 'Bulk Orders', slug: '/ecommerce-services/bulk-orders' },
    { id: 'service-2', name: 'Corporate Gifting', slug: '/ecommerce-services/corporate-gifting' },
    { id: 'service-3', name: 'Rental Services', slug: '/ecommerce-services/rental' },
    { id: 'service-4', name: 'Custom Solutions', slug: '/ecommerce-services/custom' },
  ],
  'blog': [
    { id: 'blog-category-1', name: 'Trekking Guides', slug: '/blog/trekking' },
    { id: 'blog-category-2', name: 'Camping Tips', slug: '/blog/camping' },
    { id: 'blog-category-3', name: 'Gear Reviews', slug: '/blog/reviews' },
    { id: 'blog-category-4', name: 'Adventure Stories', slug: '/blog/stories' },
  ],
}

export const categories = [
  {
    id: 'trekking',
    name: 'Trekking',
    slug: 'trekking-gear',
    description: 'Essential gear for mountain treks and hiking adventures',
    image: 'https://images.unsplash.com/photo-1551524164-6cf77f7f7e6c?w=800&h=600&fit=crop',
  },
  {
    id: 'camping',
    name: 'Camping',
    slug: 'camping-gear',
    description: 'Tents, sleeping bags, and camping essentials for outdoor stays',
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800&h=600&fit=crop',
  },
  {
    id: 'climbing',
    name: 'Climbing',
    slug: 'climbing-gear',
    description: 'Professional climbing equipment and safety gear',
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=800&h=600&fit=crop',
  },
]

export const adventureTours = [
  {
    id: 'tour-1',
    name: 'Himalayan Base Camp Trek',
    location: 'Himachal Pradesh',
    duration: '7 Days',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    badge: 'Popular',
    rating: 4.9,
  },
  {
    id: 'tour-2',
    name: 'Desert Safari Adventure',
    location: 'Rajasthan',
    duration: '3 Days',
    price: 12999,
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=600&fit=crop',
    badge: 'New',
    rating: 4.7,
  },
  {
    id: 'tour-3',
    name: 'Western Ghats Exploration',
    location: 'Kerala',
    duration: '5 Days',
    price: 18999,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    badge: null,
    rating: 4.8,
  },
  {
    id: 'tour-4',
    name: 'Rock Climbing Expedition',
    location: 'Maharashtra',
    duration: '2 Days',
    price: 8999,
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=800&h=600&fit=crop',
    badge: 'Popular',
    rating: 4.9,
  },
  {
    id: 'tour-5',
    name: 'Jungle Camping Experience',
    location: 'Madhya Pradesh',
    duration: '4 Days',
    price: 15999,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800&h=600&fit=crop',
    badge: null,
    rating: 4.6,
  },
  {
    id: 'tour-6',
    name: 'Coastal Adventure Trail',
    location: 'Goa',
    duration: '3 Days',
    price: 11999,
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=600&fit=crop',
    badge: 'New',
    rating: 4.7,
  },
]

export const gearProducts = [
  {
    id: 'gear-1',
    name: 'Premium Trekking Backpack 60L',
    description: 'Lightweight, durable backpack with multiple compartments',
    price: 5499,
    originalPrice: 6999,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 124,
    inStock: true,
  },
  {
    id: 'gear-2',
    name: '4-Season Camping Tent',
    description: 'Weather-resistant tent for all seasons',
    price: 12999,
    originalPrice: 15999,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews: 89,
    inStock: true,
  },
  {
    id: 'gear-3',
    name: 'Professional Climbing Harness',
    description: 'Comfortable harness with gear loops',
    price: 4999,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  {
    id: 'gear-4',
    name: 'Ultra-Light Sleeping Bag',
    description: 'Compact sleeping bag rated for -10°C',
    price: 6999,
    originalPrice: 8999,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 203,
    inStock: true,
  },
  {
    id: 'gear-5',
    name: 'Trekking Poles Set',
    description: 'Adjustable carbon fiber trekking poles',
    price: 2999,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1551524164-6cf77f7f7e6c?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews: 98,
    inStock: true,
  },
  {
    id: 'gear-6',
    name: 'Waterproof Hiking Boots',
    description: 'Premium boots with superior grip',
    price: 7999,
    originalPrice: 9999,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews: 312,
    inStock: true,
  },
  {
    id: 'gear-7',
    name: 'Portable Camping Stove',
    description: 'Compact gas stove for outdoor cooking',
    price: 2499,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 145,
    inStock: true,
  },
  {
    id: 'gear-8',
    name: 'Adventure Watch Pro',
    description: 'GPS-enabled watch with altimeter',
    price: 14999,
    originalPrice: 18999,
    image: 'https://images.unsplash.com/photo-1523275125684-513031cd5811?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 267,
    inStock: true,
  },
]

export const whyChooseUs = [
  {
    id: 'trust',
    icon: 'Shield',
    title: 'Trusted Quality',
    description: 'Premium gear tested by professional adventurers',
  },
  {
    id: 'shipping',
    icon: 'Truck',
    title: 'Fast Shipping',
    description: 'Quick delivery across India with secure packaging',
  },
  {
    id: 'support',
    icon: 'Headphones',
    title: 'Expert Support',
    description: '24/7 customer support from adventure enthusiasts',
  },
  {
    id: 'warranty',
    icon: 'Award',
    title: 'Warranty Coverage',
    description: 'Comprehensive warranty on all products',
  },
]

export const products = {
  'trekking-gear': gearProducts.slice(0, 6),
  'camping-gear': gearProducts.slice(2, 8),
  'climbing-gear': gearProducts.filter((p) => p.name.toLowerCase().includes('climbing') || p.name.toLowerCase().includes('harness') || p.name.toLowerCase().includes('rope')),
}

export const blogPosts = [
  {
    id: 'blog-1',
    title: 'Essential Gear for Your First Himalayan Trek',
    excerpt: 'Everything you need to know before embarking on your first high-altitude adventure',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    date: '2024-01-15',
    author: 'Adventure Team',
    category: 'Trekking',
  },
  {
    id: 'blog-2',
    title: 'Top 10 Camping Spots in India',
    excerpt: 'Discover the most beautiful and accessible camping destinations across India',
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800&h=600&fit=crop',
    date: '2024-01-10',
    author: 'Adventure Team',
    category: 'Camping',
  },
  {
    id: 'blog-3',
    title: 'Rock Climbing Safety Guide',
    excerpt: 'Learn essential safety practices for indoor and outdoor rock climbing',
    image: 'https://images.unsplash.com/photo-1517777291571-f9f42c8e5620?w=800&h=600&fit=crop',
    date: '2024-01-05',
    author: 'Adventure Team',
    category: 'Climbing',
  },
]

export const siteConfig = {
  name: 'Adventure India',
  url: 'https://www.addventureindia.com',
  description: 'Premium outdoor adventure gear and equipment for explorers across India',
  defaultSeo: {
    title: 'Adventure India - Premium Outdoor Gear & Equipment',
    description: 'Discover premium outdoor adventure gear, hiking equipment, and climbing gear. Trusted by adventurers across India.',
    keywords: 'outdoor gear, adventure equipment, hiking gear, climbing equipment, India adventure',
  },
}
